stages:
    - Build
    - Test

Build:
    tags:
        - linux
    stage: Build
    script:
        - apt update
        - apt install software-properties-common
        - apt install -y pip python3.7 virtualenv
        - virtualenv -p /usr/bin/python3 venv
        - venv/bin/pip install .

Test:
    tags:
        - linux
    stage: Test
    script:
        - echo "Hello World"
