default:
    image: 'python:3.7.7-slim'

stages:
    - Build and Test

buildandtest:
    tags:
        - linux
    stage: Build and Test
    script:
        - virtualenv venv
        - venv/bin/pip install .
