stages:
    - Build
    - Test

Build:
    tags:
        - linux
    stage: Build
    script:
        - apt-get update
        - apt-get install -y python3.7 python-pip virtualenv
        - virtualenv -p /usr/bin/python3 venv
        - venv/bin/pip install .

Test:
    tags:
        - linux
    stage: Test
    script:
        - echo "Hello World"
